// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: .proto/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file___proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MfaRequired   bool                   `protobuf:"varint,1,opt,name=mfa_required,json=mfaRequired,proto3" json:"mfa_required,omitempty"`
	ChallengeId   string                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Tokens        *TokenPair             `protobuf:"bytes,3,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file___proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetMfaRequired() bool {
	if x != nil {
		return x.MfaRequired
	}
	return false
}

func (x *LoginResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *LoginResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type TokenPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file___proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenPair) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenPair) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file___proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file___proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file___proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file___proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file___proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DeleteUserRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type EnrollMFAMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollMFAMethodRequest) Reset() {
	*x = EnrollMFAMethodRequest{}
	mi := &file___proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollMFAMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollMFAMethodRequest) ProtoMessage() {}

func (x *EnrollMFAMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollMFAMethodRequest.ProtoReflect.Descriptor instead.
func (*EnrollMFAMethodRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *EnrollMFAMethodRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type MFAMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFAMethod) Reset() {
	*x = MFAMethod{}
	mi := &file___proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAMethod) ProtoMessage() {}

func (x *MFAMethod) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAMethod.ProtoReflect.Descriptor instead.
func (*MFAMethod) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *MFAMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MFAMethod) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MFAMethod) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type EnrollMFAMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        *MFAMethod             `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	SetupUri      string                 `protobuf:"bytes,2,opt,name=setup_uri,json=setupUri,proto3" json:"setup_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollMFAMethodResponse) Reset() {
	*x = EnrollMFAMethodResponse{}
	mi := &file___proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollMFAMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollMFAMethodResponse) ProtoMessage() {}

func (x *EnrollMFAMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollMFAMethodResponse.ProtoReflect.Descriptor instead.
func (*EnrollMFAMethodResponse) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *EnrollMFAMethodResponse) GetMethod() *MFAMethod {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *EnrollMFAMethodResponse) GetSetupUri() string {
	if x != nil {
		return x.SetupUri
	}
	return ""
}

type ConfirmMFAMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodId      string                 `protobuf:"bytes,1,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmMFAMethodRequest) Reset() {
	*x = ConfirmMFAMethodRequest{}
	mi := &file___proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmMFAMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmMFAMethodRequest) ProtoMessage() {}

func (x *ConfirmMFAMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmMFAMethodRequest.ProtoReflect.Descriptor instead.
func (*ConfirmMFAMethodRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmMFAMethodRequest) GetMethodId() string {
	if x != nil {
		return x.MethodId
	}
	return ""
}

func (x *ConfirmMFAMethodRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfirmMFAMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupCodes   []string               `protobuf:"bytes,1,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmMFAMethodResponse) Reset() {
	*x = ConfirmMFAMethodResponse{}
	mi := &file___proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmMFAMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmMFAMethodResponse) ProtoMessage() {}

func (x *ConfirmMFAMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmMFAMethodResponse.ProtoReflect.Descriptor instead.
func (*ConfirmMFAMethodResponse) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmMFAMethodResponse) GetBackupCodes() []string {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

type CompleteLoginMFARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteLoginMFARequest) Reset() {
	*x = CompleteLoginMFARequest{}
	mi := &file___proto_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLoginMFARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLoginMFARequest) ProtoMessage() {}

func (x *CompleteLoginMFARequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLoginMFARequest.ProtoReflect.Descriptor instead.
func (*CompleteLoginMFARequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteLoginMFARequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CompleteLoginMFARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CreateStepUpChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodType    string                 `protobuf:"bytes,1,opt,name=method_type,json=methodType,proto3" json:"method_type,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStepUpChallengeRequest) Reset() {
	*x = CreateStepUpChallengeRequest{}
	mi := &file___proto_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStepUpChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStepUpChallengeRequest) ProtoMessage() {}

func (x *CreateStepUpChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStepUpChallengeRequest.ProtoReflect.Descriptor instead.
func (*CreateStepUpChallengeRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{14}
}

func (x *CreateStepUpChallengeRequest) GetMethodType() string {
	if x != nil {
		return x.MethodType
	}
	return ""
}

func (x *CreateStepUpChallengeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type CreateStepUpChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	MethodType    string                 `protobuf:"bytes,2,opt,name=method_type,json=methodType,proto3" json:"method_type,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStepUpChallengeResponse) Reset() {
	*x = CreateStepUpChallengeResponse{}
	mi := &file___proto_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStepUpChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStepUpChallengeResponse) ProtoMessage() {}

func (x *CreateStepUpChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStepUpChallengeResponse.ProtoReflect.Descriptor instead.
func (*CreateStepUpChallengeResponse) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{15}
}

func (x *CreateStepUpChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CreateStepUpChallengeResponse) GetMethodType() string {
	if x != nil {
		return x.MethodType
	}
	return ""
}

func (x *CreateStepUpChallengeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type VerifyStepUpChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyStepUpChallengeRequest) Reset() {
	*x = VerifyStepUpChallengeRequest{}
	mi := &file___proto_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStepUpChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStepUpChallengeRequest) ProtoMessage() {}

func (x *VerifyStepUpChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStepUpChallengeRequest.ProtoReflect.Descriptor instead.
func (*VerifyStepUpChallengeRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyStepUpChallengeRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *VerifyStepUpChallengeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyStepUpChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepUpToken   string                 `protobuf:"bytes,1,opt,name=step_up_token,json=stepUpToken,proto3" json:"step_up_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyStepUpChallengeResponse) Reset() {
	*x = VerifyStepUpChallengeResponse{}
	mi := &file___proto_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStepUpChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStepUpChallengeResponse) ProtoMessage() {}

func (x *VerifyStepUpChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStepUpChallengeResponse.ProtoReflect.Descriptor instead.
func (*VerifyStepUpChallengeResponse) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyStepUpChallengeResponse) GetStepUpToken() string {
	if x != nil {
		return x.StepUpToken
	}
	return ""
}

func (x *VerifyStepUpChallengeResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type ForgetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordRequest) Reset() {
	*x = ForgetPasswordRequest{}
	mi := &file___proto_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordRequest) ProtoMessage() {}

func (x *ForgetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{18}
}

func (x *ForgetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file___proto_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{19}
}

func (x *ResetPasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type BeginGoogleLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginGoogleLoginRequest) Reset() {
	*x = BeginGoogleLoginRequest{}
	mi := &file___proto_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginGoogleLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginGoogleLoginRequest) ProtoMessage() {}

func (x *BeginGoogleLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginGoogleLoginRequest.ProtoReflect.Descriptor instead.
func (*BeginGoogleLoginRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{20}
}

func (x *BeginGoogleLoginRequest) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

type CompleteGoogleLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteGoogleLoginRequest) Reset() {
	*x = CompleteGoogleLoginRequest{}
	mi := &file___proto_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteGoogleLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteGoogleLoginRequest) ProtoMessage() {}

func (x *CompleteGoogleLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteGoogleLoginRequest.ProtoReflect.Descriptor instead.
func (*CompleteGoogleLoginRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{21}
}

func (x *CompleteGoogleLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteGoogleLoginRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type VerifyEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file___proto_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{22}
}

func (x *VerifyEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateEmailVerificationTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailVerificationTokenRequest) Reset() {
	*x = CreateEmailVerificationTokenRequest{}
	mi := &file___proto_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailVerificationTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailVerificationTokenRequest) ProtoMessage() {}

func (x *CreateEmailVerificationTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file___proto_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailVerificationTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailVerificationTokenRequest) Descriptor() ([]byte, []int) {
	return file___proto_auth_proto_rawDescGZIP(), []int{23}
}

func (x *CreateEmailVerificationTokenRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File___proto_auth_proto protoreflect.FileDescriptor

const file___proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x11.proto/auth.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x81\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\fmfa_required\x18\x01 \x01(\bR\vmfaRequired\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\tR\vchallengeId\x12*\n" +
	"\x06tokens\x18\x03 \x01(\v2\x12.auth.v1.TokenPairR\x06tokens\"\xaa\x01\n" +
	"\tTokenPair\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"]\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"G\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\",\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"X\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"0\n" +
	"\x16EnrollMFAMethodRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\"j\n" +
	"\tMFAMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"b\n" +
	"\x17EnrollMFAMethodResponse\x12*\n" +
	"\x06method\x18\x01 \x01(\v2\x12.auth.v1.MFAMethodR\x06method\x12\x1b\n" +
	"\tsetup_uri\x18\x02 \x01(\tR\bsetupUri\"J\n" +
	"\x17ConfirmMFAMethodRequest\x12\x1b\n" +
	"\tmethod_id\x18\x01 \x01(\tR\bmethodId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"=\n" +
	"\x18ConfirmMFAMethodResponse\x12!\n" +
	"\fbackup_codes\x18\x01 \x03(\tR\vbackupCodes\"P\n" +
	"\x17CompleteLoginMFARequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"U\n" +
	"\x1cCreateStepUpChallengeRequest\x12\x1f\n" +
	"\vmethod_type\x18\x01 \x01(\tR\n" +
	"methodType\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"\x9e\x01\n" +
	"\x1dCreateStepUpChallengeResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1f\n" +
	"\vmethod_type\x18\x02 \x01(\tR\n" +
	"methodType\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"U\n" +
	"\x1cVerifyStepUpChallengeRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"b\n" +
	"\x1dVerifyStepUpChallengeResponse\x12\"\n" +
	"\rstep_up_token\x18\x01 \x01(\tR\vstepUpToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"-\n" +
	"\x15ForgetPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"O\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"4\n" +
	"\x17BeginGoogleLoginRequest\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\"F\n" +
	"\x1aCompleteGoogleLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"*\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\";\n" +
	"#CreateEmailVerificationTokenRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email2\x8f\v\n" +
	"\vAuthService\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x128\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x00\x12B\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x12.auth.v1.TokenPair\"\x00\x12@\n" +
	"\x06Logout\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x0eChangePassword\x12\x1e.auth.v1.ChangePasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\fRegisterUser\x12\x1c.auth.v1.RegisterUserRequest\x1a\r.auth.v1.User\"\x00\x12B\n" +
	"\n" +
	"DeleteUser\x12\x1a.auth.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12V\n" +
	"\x0fEnrollMFAMethod\x12\x1f.auth.v1.EnrollMFAMethodRequest\x1a .auth.v1.EnrollMFAMethodResponse\"\x00\x12Y\n" +
	"\x10ConfirmMFAMethod\x12 .auth.v1.ConfirmMFAMethodRequest\x1a!.auth.v1.ConfirmMFAMethodResponse\"\x00\x12J\n" +
	"\x10CompleteLoginMFA\x12 .auth.v1.CompleteLoginMFARequest\x1a\x12.auth.v1.TokenPair\"\x00\x12h\n" +
	"\x15CreateStepUpChallenge\x12%.auth.v1.CreateStepUpChallengeRequest\x1a&.auth.v1.CreateStepUpChallengeResponse\"\x00\x12h\n" +
	"\x15VerifyStepUpChallenge\x12%.auth.v1.VerifyStepUpChallengeRequest\x1a&.auth.v1.VerifyStepUpChallengeResponse\"\x00\x12J\n" +
	"\x0eForgetPassword\x12\x1e.auth.v1.ForgetPasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\rResetPassword\x12\x1d.auth.v1.ResetPasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x10BeginGoogleLogin\x12\x16.google.protobuf.Empty\x1a .auth.v1.BeginGoogleLoginRequest\"\x00\x12P\n" +
	"\x13CompleteGoogleLogin\x12#.auth.v1.CompleteGoogleLoginRequest\x1a\x12.auth.v1.TokenPair\"\x00\x12D\n" +
	"\vVerifyEmail\x12\x1b.auth.v1.VerifyEmailRequest\x1a\x16.google.protobuf.Empty\"\x00\x12f\n" +
	"\x1cCreateEmailVerificationToken\x12,.auth.v1.CreateEmailVerificationTokenRequest\x1a\x16.google.protobuf.Empty\"\x00B/Z-github.com/alkuwaiti/auth/pb/pbauth/v1;authv1b\x06proto3"

var (
	file___proto_auth_proto_rawDescOnce sync.Once
	file___proto_auth_proto_rawDescData []byte
)

func file___proto_auth_proto_rawDescGZIP() []byte {
	file___proto_auth_proto_rawDescOnce.Do(func() {
		file___proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file___proto_auth_proto_rawDesc), len(file___proto_auth_proto_rawDesc)))
	})
	return file___proto_auth_proto_rawDescData
}

var file___proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file___proto_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),                        // 0: auth.v1.LoginRequest
	(*LoginResponse)(nil),                       // 1: auth.v1.LoginResponse
	(*TokenPair)(nil),                           // 2: auth.v1.TokenPair
	(*RefreshTokenRequest)(nil),                 // 3: auth.v1.RefreshTokenRequest
	(*ChangePasswordRequest)(nil),               // 4: auth.v1.ChangePasswordRequest
	(*RegisterUserRequest)(nil),                 // 5: auth.v1.RegisterUserRequest
	(*User)(nil),                                // 6: auth.v1.User
	(*DeleteUserRequest)(nil),                   // 7: auth.v1.DeleteUserRequest
	(*EnrollMFAMethodRequest)(nil),              // 8: auth.v1.EnrollMFAMethodRequest
	(*MFAMethod)(nil),                           // 9: auth.v1.MFAMethod
	(*EnrollMFAMethodResponse)(nil),             // 10: auth.v1.EnrollMFAMethodResponse
	(*ConfirmMFAMethodRequest)(nil),             // 11: auth.v1.ConfirmMFAMethodRequest
	(*ConfirmMFAMethodResponse)(nil),            // 12: auth.v1.ConfirmMFAMethodResponse
	(*CompleteLoginMFARequest)(nil),             // 13: auth.v1.CompleteLoginMFARequest
	(*CreateStepUpChallengeRequest)(nil),        // 14: auth.v1.CreateStepUpChallengeRequest
	(*CreateStepUpChallengeResponse)(nil),       // 15: auth.v1.CreateStepUpChallengeResponse
	(*VerifyStepUpChallengeRequest)(nil),        // 16: auth.v1.VerifyStepUpChallengeRequest
	(*VerifyStepUpChallengeResponse)(nil),       // 17: auth.v1.VerifyStepUpChallengeResponse
	(*ForgetPasswordRequest)(nil),               // 18: auth.v1.ForgetPasswordRequest
	(*ResetPasswordRequest)(nil),                // 19: auth.v1.ResetPasswordRequest
	(*BeginGoogleLoginRequest)(nil),             // 20: auth.v1.BeginGoogleLoginRequest
	(*CompleteGoogleLoginRequest)(nil),          // 21: auth.v1.CompleteGoogleLoginRequest
	(*VerifyEmailRequest)(nil),                  // 22: auth.v1.VerifyEmailRequest
	(*CreateEmailVerificationTokenRequest)(nil), // 23: auth.v1.CreateEmailVerificationTokenRequest
	(*timestamppb.Timestamp)(nil),               // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                       // 25: google.protobuf.Empty
}
var file___proto_auth_proto_depIdxs = []int32{
	2,  // 0: auth.v1.LoginResponse.tokens:type_name -> auth.v1.TokenPair
	24, // 1: auth.v1.MFAMethod.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: auth.v1.EnrollMFAMethodResponse.method:type_name -> auth.v1.MFAMethod
	24, // 3: auth.v1.CreateStepUpChallengeResponse.expires_at:type_name -> google.protobuf.Timestamp
	25, // 4: auth.v1.AuthService.Ping:input_type -> google.protobuf.Empty
	0,  // 5: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	3,  // 6: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	3,  // 7: auth.v1.AuthService.Logout:input_type -> auth.v1.RefreshTokenRequest
	4,  // 8: auth.v1.AuthService.ChangePassword:input_type -> auth.v1.ChangePasswordRequest
	5,  // 9: auth.v1.AuthService.RegisterUser:input_type -> auth.v1.RegisterUserRequest
	7,  // 10: auth.v1.AuthService.DeleteUser:input_type -> auth.v1.DeleteUserRequest
	8,  // 11: auth.v1.AuthService.EnrollMFAMethod:input_type -> auth.v1.EnrollMFAMethodRequest
	11, // 12: auth.v1.AuthService.ConfirmMFAMethod:input_type -> auth.v1.ConfirmMFAMethodRequest
	13, // 13: auth.v1.AuthService.CompleteLoginMFA:input_type -> auth.v1.CompleteLoginMFARequest
	14, // 14: auth.v1.AuthService.CreateStepUpChallenge:input_type -> auth.v1.CreateStepUpChallengeRequest
	16, // 15: auth.v1.AuthService.VerifyStepUpChallenge:input_type -> auth.v1.VerifyStepUpChallengeRequest
	18, // 16: auth.v1.AuthService.ForgetPassword:input_type -> auth.v1.ForgetPasswordRequest
	19, // 17: auth.v1.AuthService.ResetPassword:input_type -> auth.v1.ResetPasswordRequest
	25, // 18: auth.v1.AuthService.BeginGoogleLogin:input_type -> google.protobuf.Empty
	21, // 19: auth.v1.AuthService.CompleteGoogleLogin:input_type -> auth.v1.CompleteGoogleLoginRequest
	22, // 20: auth.v1.AuthService.VerifyEmail:input_type -> auth.v1.VerifyEmailRequest
	23, // 21: auth.v1.AuthService.CreateEmailVerificationToken:input_type -> auth.v1.CreateEmailVerificationTokenRequest
	25, // 22: auth.v1.AuthService.Ping:output_type -> google.protobuf.Empty
	1,  // 23: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	2,  // 24: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.TokenPair
	25, // 25: auth.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	25, // 26: auth.v1.AuthService.ChangePassword:output_type -> google.protobuf.Empty
	6,  // 27: auth.v1.AuthService.RegisterUser:output_type -> auth.v1.User
	25, // 28: auth.v1.AuthService.DeleteUser:output_type -> google.protobuf.Empty
	10, // 29: auth.v1.AuthService.EnrollMFAMethod:output_type -> auth.v1.EnrollMFAMethodResponse
	12, // 30: auth.v1.AuthService.ConfirmMFAMethod:output_type -> auth.v1.ConfirmMFAMethodResponse
	2,  // 31: auth.v1.AuthService.CompleteLoginMFA:output_type -> auth.v1.TokenPair
	15, // 32: auth.v1.AuthService.CreateStepUpChallenge:output_type -> auth.v1.CreateStepUpChallengeResponse
	17, // 33: auth.v1.AuthService.VerifyStepUpChallenge:output_type -> auth.v1.VerifyStepUpChallengeResponse
	25, // 34: auth.v1.AuthService.ForgetPassword:output_type -> google.protobuf.Empty
	25, // 35: auth.v1.AuthService.ResetPassword:output_type -> google.protobuf.Empty
	20, // 36: auth.v1.AuthService.BeginGoogleLogin:output_type -> auth.v1.BeginGoogleLoginRequest
	2,  // 37: auth.v1.AuthService.CompleteGoogleLogin:output_type -> auth.v1.TokenPair
	25, // 38: auth.v1.AuthService.VerifyEmail:output_type -> google.protobuf.Empty
	25, // 39: auth.v1.AuthService.CreateEmailVerificationToken:output_type -> google.protobuf.Empty
	22, // [22:40] is the sub-list for method output_type
	4,  // [4:22] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file___proto_auth_proto_init() }
func file___proto_auth_proto_init() {
	if File___proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file___proto_auth_proto_rawDesc), len(file___proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file___proto_auth_proto_goTypes,
		DependencyIndexes: file___proto_auth_proto_depIdxs,
		MessageInfos:      file___proto_auth_proto_msgTypes,
	}.Build()
	File___proto_auth_proto = out.File
	file___proto_auth_proto_goTypes = nil
	file___proto_auth_proto_depIdxs = nil
}
