// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Action    string
	IpAddress sql.NullString
	UserAgent sql.NullString
	CreatedAt sql.NullTime
	ActorID   uuid.NullUUID
	Context   pqtype.NullRawMessage
}

type EmailVerificationToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	ConsumedAt sql.NullTime
	CreatedAt  time.Time
}

type MfaBackupCode struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CodeHash   string
	ConsumedAt sql.NullTime
	CreatedAt  time.Time
}

type MfaChallenge struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	MfaMethodID   uuid.UUID
	ChallengeType string
	ExpiresAt     time.Time
	ConsumedAt    sql.NullTime
	CreatedAt     time.Time
	Scope         string
	Attempts      int32
	RememberMe    bool
}

type OutboxEvent struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       json.RawMessage
	CreatedAt     time.Time
	PublishedAt   sql.NullTime
	RetryCount    int32
	LastError     sql.NullString
	FailedAt      sql.NullTime
}

type Passkey struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	CredentialID []byte
	PublicKey    []byte
	SignCount    int64
	Transports   []string
	Name         sql.NullString
	CreatedAt    time.Time
	LastUsedAt   sql.NullTime
}

type PasswordResetToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	ConsumedAt sql.NullTime
	CreatedAt  time.Time
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshToken     string
	UserAgent        sql.NullString
	IpAddress        sql.NullString
	CreatedAt        sql.NullTime
	ExpiresAt        time.Time
	RevokedAt        sql.NullTime
	RevocationReason sql.NullString
	CompromisedAt    sql.NullTime
}

type SocialAccount struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	CreatedAt      time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    sql.NullString
	IsEmailVerified bool
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	DeletionReason  sql.NullString
	MfaEnabled      bool
}

type UserMfaMethod struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Type             string
	SecretCiphertext []byte
	ConfirmedAt      sql.NullTime
	CreatedAt        time.Time
	ExpiresAt        sql.NullTime
}

type UserRole struct {
	UserID     uuid.UUID
	RoleID     uuid.UUID
	AssignedAt sql.NullTime
}

type WebauthnChallenge struct {
	Challenge string
	UserID    uuid.UUID
	ExpiresAt time.Time
}
