// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthAuditLog struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Action    string
	IpAddress sql.NullString
	UserAgent sql.NullString
	CreatedAt sql.NullTime
}

type AuthToken struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	TokenHash string
	Type      string
	ExpiresAt time.Time
	Used      sql.NullBool
	CreatedAt sql.NullTime
}

type Permission struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshToken     string
	UserAgent        sql.NullString
	IpAddress        sql.NullString
	CreatedAt        sql.NullTime
	ExpiresAt        time.Time
	RevokedAt        sql.NullTime
	RevocationReason sql.NullString
	CompromisedAt    sql.NullTime
}

type SocialAccount struct {
	ID             uuid.UUID
	UserID         uuid.NullUUID
	Provider       string
	ProviderUserID string
	AccessToken    sql.NullString
	RefreshToken   sql.NullString
	CreatedAt      sql.NullTime
}

type TwoFactorMethod struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	Method      string
	Secret      sql.NullString
	PhoneNumber sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
}

type User struct {
	ID              uuid.UUID
	Email           string
	Username        string
	PasswordHash    string
	IsEmailVerified bool
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	DeletionReason  sql.NullString
}

type UserRole struct {
	UserID     uuid.UUID
	RoleID     uuid.UUID
	AssignedAt sql.NullTime
}
