// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthAuditLog struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Action    string
	IpAddress sql.NullString
	UserAgent sql.NullString
	CreatedAt sql.NullTime
	ActorID   uuid.NullUUID
	Context   pqtype.NullRawMessage
}

type AuthToken struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	TokenHash string
	Type      string
	ExpiresAt time.Time
	Used      sql.NullBool
	CreatedAt sql.NullTime
}

type MfaChallenge struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	MfaMethodID   uuid.UUID
	ChallengeType string
	ExpiresAt     time.Time
	ConsumedAt    sql.NullTime
	CreatedAt     time.Time
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshToken     string
	UserAgent        sql.NullString
	IpAddress        sql.NullString
	CreatedAt        sql.NullTime
	ExpiresAt        time.Time
	RevokedAt        sql.NullTime
	RevocationReason sql.NullString
	CompromisedAt    sql.NullTime
}

type SocialAccount struct {
	ID             uuid.UUID
	UserID         uuid.NullUUID
	Provider       string
	ProviderUserID string
	AccessToken    sql.NullString
	RefreshToken   sql.NullString
	CreatedAt      sql.NullTime
}

type User struct {
	ID              uuid.UUID
	Email           string
	Username        string
	PasswordHash    string
	IsEmailVerified bool
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	DeletionReason  sql.NullString
	MfaEnabled      bool
}

type UserMfaMethod struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Type             string
	SecretCiphertext []byte
	ConfirmedAt      sql.NullTime
	CreatedAt        time.Time
}

type UserRole struct {
	UserID     uuid.UUID
	RoleID     uuid.UUID
	AssignedAt sql.NullTime
}
