// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id, assigned_at)
VALUES ($1, $2, NOW())
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const confirmUserMFAMethod = `-- name: ConfirmUserMFAMethod :exec
UPDATE user_mfa_methods
SET confirmed_at = now()
WHERE id = $1
  AND confirmed_at IS NULL
`

func (q *Queries) ConfirmUserMFAMethod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, confirmUserMFAMethod, id)
	return err
}

const consumeChallenge = `-- name: ConsumeChallenge :exec
UPDATE mfa_challenges
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, consumeChallenge, id)
	return err
}

const createAuditLog = `-- name: CreateAuditLog :exec

INSERT INTO auth_audit_logs (user_id, action, ip_address, user_agent, actor_id, context)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	UserID    uuid.NullUUID
	Action    string
	IpAddress sql.NullString
	UserAgent sql.NullString
	ActorID   uuid.NullUUID
	Context   pqtype.NullRawMessage
}

// audit
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.IpAddress,
		arg.UserAgent,
		arg.ActorID,
		arg.Context,
	)
	return err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO mfa_challenges (
  user_id, mfa_method_id, challenge_type, expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, mfa_method_id, challenge_type, expires_at, consumed_at, created_at
`

type CreateChallengeParams struct {
	UserID        uuid.UUID
	MfaMethodID   uuid.UUID
	ChallengeType string
	ExpiresAt     time.Time
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (MfaChallenge, error) {
	row := q.db.QueryRowContext(ctx, createChallenge,
		arg.UserID,
		arg.MfaMethodID,
		arg.ChallengeType,
		arg.ExpiresAt,
	)
	var i MfaChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MfaMethodID,
		&i.ChallengeType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token, user_agent, ip_address, created_at, expires_at, revoked_at, revocation_reason, compromised_at
`

type CreateSessionParams struct {
	UserID       uuid.UUID
	RefreshToken string
	UserAgent    sql.NullString
	IpAddress    sql.NullString
	ExpiresAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CompromisedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, email, password_hash , created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, email, username, password_hash, is_email_verified, is_active, created_at, updated_at, deleted_at, deletion_reason, mfa_enabled
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
}

// users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.MfaEnabled,
	)
	return i, err
}

const createUserMFAMethod = `-- name: CreateUserMFAMethod :one

INSERT INTO user_mfa_methods (
  user_id, type, secret_ciphertext
)
VALUES ($1, $2, $3)
RETURNING id, user_id, type, secret_ciphertext, confirmed_at, created_at
`

type CreateUserMFAMethodParams struct {
	UserID           uuid.UUID
	Type             string
	SecretCiphertext []byte
}

// mfa
func (q *Queries) CreateUserMFAMethod(ctx context.Context, arg CreateUserMFAMethodParams) (UserMfaMethod, error) {
	row := q.db.QueryRowContext(ctx, createUserMFAMethod, arg.UserID, arg.Type, arg.SecretCiphertext)
	var i UserMfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.SecretCiphertext,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
UPDATE users
SET
  deleted_at = NOW(),
  deletion_reason = $1
WHERE id = $2
  AND deleted_at IS NULL
`

type DeleteUserParams struct {
	DeletionReason sql.NullString
	ID             uuid.UUID
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, arg.DeletionReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveChallenge = `-- name: GetActiveChallenge :one
SELECT id, user_id, mfa_method_id, expires_at, consumed_at
FROM mfa_challenges
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

type GetActiveChallengeRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	MfaMethodID uuid.UUID
	ExpiresAt   time.Time
	ConsumedAt  sql.NullTime
}

func (q *Queries) GetActiveChallenge(ctx context.Context, id uuid.UUID) (GetActiveChallengeRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveChallenge, id)
	var i GetActiveChallengeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MfaMethodID,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getMFAMethodByID = `-- name: GetMFAMethodByID :one
SELECT id, user_id, type, secret_ciphertext, confirmed_at, created_at FROM user_mfa_methods
WHERE id = $1
`

func (q *Queries) GetMFAMethodByID(ctx context.Context, id uuid.UUID) (UserMfaMethod, error) {
	row := q.db.QueryRowContext(ctx, getMFAMethodByID, id)
	var i UserMfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.SecretCiphertext,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMFAMethodsConfirmedByUser = `-- name: GetMFAMethodsConfirmedByUser :many
SELECT id, user_id, type, confirmed_at, created_at
FROM user_mfa_methods
WHERE user_id = $1
  AND confirmed_at IS NOT NULL
`

type GetMFAMethodsConfirmedByUserRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	ConfirmedAt sql.NullTime
	CreatedAt   time.Time
}

func (q *Queries) GetMFAMethodsConfirmedByUser(ctx context.Context, userID uuid.UUID) ([]GetMFAMethodsConfirmedByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getMFAMethodsConfirmedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMFAMethodsConfirmedByUserRow
	for rows.Next() {
		var i GetMFAMethodsConfirmedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.ConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleIDByName = `-- name: GetRoleIDByName :one

SELECT id
FROM roles
WHERE name = $1
`

// authorization
func (q *Queries) GetRoleIDByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getRoleIDByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one

SELECT id, user_id, refresh_token, user_agent, ip_address, created_at, expires_at, revoked_at, revocation_reason, compromised_at FROM sessions WHERE refresh_token = $1
`

// sessions
func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CompromisedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  u.id, u.email, u.username, u.password_hash, u.is_email_verified, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.deletion_reason, u.mfa_enabled,
  ARRAY_AGG(r.name)::text[] AS roles
FROM users u
JOIN user_roles ur ON u.id = ur.user_id
JOIN roles r ON ur.role_id = r.id
WHERE u.email = $1
GROUP BY u.id
`

type GetUserByEmailRow struct {
	ID              uuid.UUID
	Email           string
	Username        string
	PasswordHash    string
	IsEmailVerified bool
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	DeletionReason  sql.NullString
	MfaEnabled      bool
	Roles           []string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.MfaEnabled,
		pq.Array(&i.Roles),
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  u.id, u.email, u.username, u.password_hash, u.is_email_verified, u.is_active, u.created_at, u.updated_at, u.deleted_at, u.deletion_reason, u.mfa_enabled,
  ARRAY_AGG(r.name)::text[] AS roles
FROM users u
JOIN user_roles ur ON u.id = ur.user_id
JOIN roles r ON ur.role_id = r.id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserByIDRow struct {
	ID              uuid.UUID
	Email           string
	Username        string
	PasswordHash    string
	IsEmailVerified bool
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	DeletionReason  sql.NullString
	MfaEnabled      bool
	Roles           []string
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.MfaEnabled,
		pq.Array(&i.Roles),
	)
	return i, err
}

const markSessionsCompromised = `-- name: MarkSessionsCompromised :exec
UPDATE sessions
SET compromised_at = NOW()
WHERE user_id = $1
  AND compromised_at IS NULL
`

func (q *Queries) MarkSessionsCompromised(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markSessionsCompromised, userID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET 
  revoked_at = NOW(),
  revocation_reason = $1
WHERE user_id = $2
AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	RevocationReason sql.NullString
	UserID           uuid.UUID
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserSessions, arg.RevocationReason, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions 
SET 
  revoked_at = NOW(),
  revocation_reason = $1
WHERE id = $2
AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevocationReason sql.NullString
	ID               uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevocationReason, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE username = $1 OR email = $2
)
`

type UserExistsParams struct {
	Username string
	Email    string
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, arg.Username, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userHasActiveMFAMethod = `-- name: UserHasActiveMFAMethod :one
SELECT COUNT(*) > 0 AS exists
FROM user_mfa_methods
WHERE user_id = $1
  AND type = $2
  AND confirmed_at IS NOT NULL
`

type UserHasActiveMFAMethodParams struct {
	UserID uuid.UUID
	Type   string
}

func (q *Queries) UserHasActiveMFAMethod(ctx context.Context, arg UserHasActiveMFAMethodParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasActiveMFAMethod, arg.UserID, arg.Type)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
