package auth

import "errors"

var (
	ErrForbidden                     = errors.New("forbidden")
	ErrUserExists                    = errors.New("user exists")
	ErrUserNotFound                  = errors.New("user not found")
	ErrInvalidCredentials            = errors.New("invalid credentials")
	ErrPasswordReuse                 = errors.New("new password cannot be old password")
	ErrRefreshDisabled               = errors.New("refresh tokens disabled by system")
	ErrChallengeExpired              = errors.New("challenge expired")
	ErrChallengeConsumed             = errors.New("challenge already consumed")
	ErrInvalidMFACode                = errors.New("incorrect mfa code")
	ErrInvalidMFAChallenge           = errors.New("invalid mfa challenge")
	ErrInvalidMFAChallengeType       = errors.New("invalid mfa challenge type")
	ErrInvalidMFAMethodType          = errors.New("invalid mfa method type")
	ErrInvalidMFAChallengeScope      = errors.New("invalid mfa challenge scope")
	ErrMFAMethodAlreadyEnrolled      = errors.New("MFA method already enrolled")
	ErrMFAMethodExpired              = errors.New("method enrollment window expired")
	ErrMethodAlreadyConfirmed        = errors.New("already confirmed")
	ErrInvalidEmail                  = errors.New("invalid email")
	ErrInvalidDeletionReason         = errors.New("invalid deletion reason")
	ErrInvalidResetToken             = errors.New("invalid reset token")
	ErrInvalidEmailVerificationToken = errors.New("invalid email verification token")
	ErrUnverifiedGoogleEmail         = errors.New("unverified google email")
	ErrChallengeMismatch             = errors.New("challenges mismatch")
	ErrInvalidOrigin                 = errors.New("invalid origin")
	ErrInvalidClientData             = errors.New("invalid client data")
	ErrNoAttestedData                = errors.New("no attested credential data")
	ErrCredentialIDMismatch          = errors.New("credential id mismtach")
	ErrInvalidRPID                   = errors.New("invalid RP ID")
)
