name: Build & Push Image

on:
  push:
    branches: [main]
  # TODO: remove. for testing only.
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Run tests
        run: go test -tags=integration ./...

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image name
        run: |
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}/auth-service:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build & push image
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

